### ISSUE TITLE
Frontend: Egyszerre csak 1 listázás legyen megjelenítve

### ISSUE THREAD

**Issue by ShuoTheOne** [Mrk-PTi/Aquapark_C1#48]
ac:

- Az oldalon bármelyik "List" gombra kattintva, csak az a lista jelenik meg alul a messagedivben.

**Comment by ShuoTheOne** [comment]
ac:
- Az oldalon bármelyik "List" gombra kattintva, csak az a lista jelenik meg alul.

**Comment by Mrk-PTi** [comment]
Nem

**Comment by Mrk-PTi** [comment]
Igen

**Comment by Mrk-PTi** [comment]
Igen vagy nem?

**Comment by ShuoTheOne** [comment]
Alternatívan megoldva: Listázás után frissítve az oldalt megoldódik a probléma

**Comment by Mrk-PTi** [comment]
Ez egy comment szekció!

**Comment by ShuoTheOne** [comment]
Alternatív megoldás: 
 - A refresh buttonnel ki lehet küszöbölni a problémát
