### ISSUE TITLE
Explaining use cases

### ISSUE THREAD

**Issue by K-SDavid** [Mrk-PTi/Aquapark_C1#6]
Use case diagram részletezése

AC:
 - srs.md fájlban

![UseCase](https://user-images.githubusercontent.com/55917870/95682556-1c4b1b80-0be6-11eb-96d4-201deaf59c79.png)

Kép feltöltése a srs.md fájlba.

**Comment by Mrk-PTi** [comment]
Use Case diagram képe feltöltve.

**Comment by Mrk-PTi** [comment]
#closed
